apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ntxzip7aq-python 
  janus-idp.io/tekton: ntxzip7aq-python
  backstage.io/kubernetes-id: ntxzip7aq-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ntxzip7aq-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml